{{-- index.blade.php --}}
@extends('layout')

@section('content')
<div class="user-types-container mt-4">
    <div class="page-header">
        <div class="header-content">
            <h2 class="page-title">Reports</h2>
            <p class="page-subtitle">View and generate a variety of reports for visitor and user activity.</p>
        </div>
    </div>

    <div class="table-card py-4">
        <div class="table-container">
            <h5 class="card-title text-start mb-3">All Reports</h5>
            <div class="table-responsive-sm table-responsive-md table-responsive-lg">
                <table class="table modern-table  border border-dark-subtle" id="reportsTable">
                    <thead>
                        <tr>
                            <th>Report ID</th>
                            <th>Report Name</th>
                            <th>Generated By</th>
                            <th>Date Generated</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{-- Data will be populated here by DataTables --}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    let default_fields = {!! json_encode(config('constants.crud.reports')) !!};
</script>
@vite(['resources/js/Reports.js'])
@vite('resources/sass/app.scss')
@endpush